[project]
name = "is-this-gonna-be-a-problem"
version = "0.1.0"
description = "Is This Order Gonna Be a Problem?"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
]
